# Generated by Django 5.1.15 on 2026-09-04 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('theatre', 'Theatre'), ('music', 'Music'), ('film', 'Film'), ('exhibition', 'Exhibition'), ('talk', 'Talk / lecture'), ('food', 'Food & drink'), ('event', 'Event'), ('unusual', 'Unusual experience'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(help_text='Reader-facing description of the opportunity.')),
                ('editorial_note', models.TextField(blank=True, help_text='Internal notes on why this is worth recommending and to whom. Used as raw material for the recommendation rationale.')),
                ('price_tier', models.CharField(choices=[('free', 'Free'), ('budget', 'Budget (under ~£20)'), ('moderate', 'Moderate (~£20-£50)'), ('premium', 'Premium (~£50-£100)'), ('splurge', 'Splurge (£100+)')], max_length=20)),
                ('price_display', models.CharField(blank=True, help_text="Human-readable price, e.g. '£25-£45'.", max_length=60)),
                ('location_name', models.CharField(blank=True, help_text='Venue name.', max_length=200)),
                ('location_area', models.CharField(help_text="City or area used for matching against a reader's location, e.g. 'London'.", max_length=120)),
                ('is_online', models.BooleanField(default=False, help_text="Doesn't require travel, e.g. a livestream or film to watch at home.")),
                ('booking_url', models.URLField(max_length=500)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for ongoing / no fixed end date.', null=True)),
                ('critic_rating', models.DecimalField(blank=True, decimal_places=1, help_text='Rating out of 5, if available.', max_digits=3, null=True)),
                ('critic_rating_source', models.CharField(blank=True, help_text="e.g. 'The Guardian, 4/5'.", max_length=120)),
                ('mainstream_to_unusual', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='1 = mainstream/crowd-pleasing, 5 = niche/unusual.')),
                ('intimate_to_large_scale', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='1 = intimate/small-scale, 5 = big/large-scale.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='opportunities', to='opportunities.tag')),
            ],
            options={
                'verbose_name_plural': 'opportunities',
                'ordering': ['-created_at'],
            },
        ),
    ]
