# Generated by Django 5.1.15 on 2026-09-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(blank=True, choices=[('theatre', 'Theatre'), ('music', 'Music'), ('film', 'Film'), ('exhibition', 'Exhibition'), ('talk', 'Talk / lecture'), ('food', 'Food & drink'), ('event', 'Event'), ('unusual', 'Unusual experience'), ('other', 'Other')], help_text='Which broad category this interest sits under. Drives which tags a reader is shown during onboarding. Blank = always shown.', max_length=20),
        ),
    ]
