# Generated by Django 5.1.15 on 2026-09-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_seed_interest_taxonomy'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='critic_quote',
            field=models.TextField(blank=True, help_text='A short quote from an actual review, if you have one. Only ever paste something real - the newsletter attributes it by name, and nothing will invent one for you.'),
        ),
    ]
