# Generated by Django 5.1.15 on 2026-09-08 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_opportunity_critic_quote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['-created_at'], 'verbose_name': 'listing', 'verbose_name_plural': 'listings'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['category', 'name'], 'verbose_name': 'interest', 'verbose_name_plural': 'interests'},
        ),
    ]
