# Generated by Django 5.1.15 on 2026-09-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0005_alter_opportunity_options_alter_tag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='found_by_ai',
            field=models.BooleanField(default=False, help_text='Researched by AI rather than written by an editor. Always a draft until someone has checked it.'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='sources',
            field=models.JSONField(blank=True, default=list, help_text='Pages the research read, as {title, url}. Empty for a listing an editor wrote.'),
        ),
        migrations.AddField(
            model_name='tag',
            name='origin',
            field=models.CharField(choices=[('editor', 'Added by an editor'), ('reader', 'Asked for by readers')], default='editor', help_text='Whether an editor added this or readers asked for it.', max_length=10),
        ),
        migrations.AddField(
            model_name='tag',
            name='times_requested',
            field=models.PositiveIntegerField(default=0, help_text='How many readers typed this in themselves. The queue of what to find listings for, in order.'),
        ),
    ]
