# Generated by Django 5.1.15 on 2026-09-09 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0006_opportunity_found_by_ai_opportunity_sources_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['-created_at']},
        ),
    ]
