# Generated by Django 5.1.15 on 2026-09-17 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0007_alter_opportunity_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='category',
            field=models.CharField(choices=[('theatre', 'Theatre'), ('music', 'Music'), ('film', 'Film'), ('exhibition', 'Exhibition'), ('talk', 'Talk / lecture'), ('food', 'Food & drink'), ('event', 'Event'), ('unusual', 'Unusual experience'), ('book', 'Books'), ('listen', 'New music'), ('watch', 'TV & streaming'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(blank=True, choices=[('theatre', 'Theatre'), ('music', 'Music'), ('film', 'Film'), ('exhibition', 'Exhibition'), ('talk', 'Talk / lecture'), ('food', 'Food & drink'), ('event', 'Event'), ('unusual', 'Unusual experience'), ('book', 'Books'), ('listen', 'New music'), ('watch', 'TV & streaming'), ('other', 'Other')], help_text='Which broad category this interest sits under. Drives which tags a reader is shown during onboarding. Blank = always shown.', max_length=20),
        ),
        migrations.CreateModel(
            name='CriticReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.CharField(help_text='e.g. The Guardian, Time Out.', max_length=80)),
                ('stars', models.DecimalField(blank=True, decimal_places=1, help_text='Out of 5, halves allowed. Blank if the review has no star rating.', max_digits=2, null=True)),
                ('url', models.URLField(help_text='The review itself, not a search page.', max_length=500)),
                ('quote', models.CharField(blank=True, help_text='A short line copied exactly from the review, if you want one quoted.', max_length=300)),
                ('verified', models.CharField(blank=True, choices=[('', 'Not checked yet'), ('page', 'Confirmed on the review page'), ('editor', 'Checked by an editor')], default='', max_length=10)),
                ('found_by_ai', models.BooleanField(default=False)),
                ('check_note', models.CharField(blank=True, help_text='What the automatic check found, for whoever verifies it by hand.', max_length=200)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='opportunities.opportunity')),
            ],
            options={
                'ordering': ['publication'],
                'constraints': [models.UniqueConstraint(fields=('opportunity', 'publication'), name='one_review_per_publication')],
            },
        ),
    ]
