# Generated by Django 5.1.15 on 2026-09-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0010_new_releases_means_cinema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='category',
            field=models.CharField(choices=[('theatre', 'Theatre'), ('music', 'Music'), ('film', 'Film'), ('exhibition', 'Exhibition'), ('talk', 'Talk / lecture'), ('food', 'Food & drink'), ('event', 'Event'), ('sport', 'Sport'), ('unusual', 'Unusual experience'), ('book', 'Books'), ('listen', 'New music'), ('watch', 'TV & streaming'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(blank=True, choices=[('theatre', 'Theatre'), ('music', 'Music'), ('film', 'Film'), ('exhibition', 'Exhibition'), ('talk', 'Talk / lecture'), ('food', 'Food & drink'), ('event', 'Event'), ('sport', 'Sport'), ('unusual', 'Unusual experience'), ('book', 'Books'), ('listen', 'New music'), ('watch', 'TV & streaming'), ('other', 'Other')], help_text='Which broad category this interest sits under. Drives which tags a reader is shown during onboarding. Blank = always shown.', max_length=20),
        ),
    ]
