# Generated by Django 5.1.15 on 2026-09-07 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0004_opportunity_critic_quote'),
        ('readers', '0008_remove_reader_edit_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="For you, not the reader - e.g. 'Frieze weekend' or 'Venue change'.", max_length=120)),
                ('subject', models.CharField(help_text="Placeholders: {first_name}, and {name} (their first name plus a comma, or nothing if we don't have one).", max_length=200)),
                ('brief', models.TextField(blank=True, help_text="What this email is about, in your words: the facts, why it matters, what you'd like readers to do. This is the only source of facts the AI may use - if it isn't here, it won't be in the email.")),
                ('body', models.TextField(blank=True, help_text="The email as you'd write it yourself, paragraphs separated by blank lines. With personalisation on it's source material and each reader gets their own version; off, it goes out exactly as written. {first_name} works here too.")),
                ('personalise', models.BooleanField(default=True, help_text="Write each reader's version from the brief and their profile, in the newsletter's voice. If AI is off or unavailable, the body goes out as written instead.", verbose_name='Personalise with AI')),
                ('link_label', models.CharField(blank=True, default='Book / learn more', help_text='Text on the button under the email, if there is a link.', max_length=60)),
                ('link_url', models.URLField(blank=True, help_text='Optional button under the text.')),
                ('audience_categories', models.JSONField(blank=True, default=list, help_text='Only readers who follow at least one of these. Empty means no restriction.')),
                ('audience_location', models.CharField(blank=True, help_text="Only readers whose location contains this, e.g. 'London'. Empty means everywhere.", max_length=120)),
                ('send_at', models.DateTimeField(blank=True, help_text="When to send. Leave blank to send as soon as it's scheduled. The scheduler checks every 15 minutes, so a time is honoured to within that.", null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, help_text='The most recent failure, if any. Per-reader detail is in the deliveries below.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audience_tags', models.ManyToManyField(blank=True, help_text='Only readers who picked at least one of these interests. Empty means no restriction.', related_name='campaigns', to='opportunities.tag')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('personalised', models.BooleanField(default=False, help_text="Whether AI wrote this reader's version.")),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body_text', models.TextField(blank=True, help_text='Exactly what this reader was sent.')),
                ('provider_message_id', models.CharField(blank=True, max_length=120)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='campaigns.campaign')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_deliveries', to='readers.reader')),
            ],
            options={
                'verbose_name_plural': 'campaign deliveries',
                'ordering': ['campaign', 'pk'],
                'unique_together': {('campaign', 'reader')},
            },
        ),
    ]
