# Generated by Django 5.1.15 on 2026-09-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='send_at',
            field=models.DateTimeField(blank=True, help_text="When to send. Leave blank to send as soon as it's scheduled. The scheduler checks every few minutes, so a time is honoured to within that.", null=True),
        ),
    ]
