# Generated by Django 5.1.15 on 2026-09-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_send_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='ends_on',
            field=models.DateField(blank=True, help_text='Last day it may run. Blank means it repeats until you cancel it.', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='frequency',
            field=models.CharField(choices=[('once', 'Once'), ('daily', 'Every day'), ('weekly', 'Every week'), ('fortnightly', 'Every two weeks'), ('monthly', 'Every month')], default='once', help_text='Once, or on repeat between the start and end dates below. A repeating campaign emails its whole audience again on every run.', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='last_run_on',
            field=models.DateField(blank=True, editable=False, help_text='Set after each run so one day never sends twice.', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='send_hour',
            field=models.PositiveSmallIntegerField(default=9, help_text="Hour of the day a repeating campaign goes out, 0-23, in the site's time zone."),
        ),
        migrations.AddField(
            model_name='campaign',
            name='starts_on',
            field=models.DateField(blank=True, help_text='First day a repeating campaign may run. Blank means it may run from now.', null=True),
        ),
    ]
