# Generated by Django 5.1.15 on 2026-09-09 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaigndelivery_token'),
        ('opportunities', '0006_opportunity_found_by_ai_opportunity_sources_and_more'),
        ('readers', '0008_remove_reader_edit_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='For you, not the reader.', max_length=120)),
                ('kind', models.CharField(choices=[('newsletter', "Newsletter — each reader's own picks"), ('campaign', 'Campaign — one message, from a brief')], default='newsletter', max_length=20)),
                ('audience_categories', models.JSONField(blank=True, default=list)),
                ('audience_location', models.CharField(blank=True, max_length=120)),
                ('auto_select_audience', models.BooleanField(default=False, help_text="Before each run, AI re-reads the brief and sets the interests, categories and location. Off means what you set is what's used.", verbose_name='Let AI pick the audience')),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('brief', models.TextField(blank=True, help_text="What it's about, in your words. The only source of facts.")),
                ('body', models.TextField(blank=True)),
                ('auto_write', models.BooleanField(default=True, help_text='Each reader gets their own version written from the brief. Off means the body goes out as written.', verbose_name='Let AI write it')),
                ('auto_tag', models.BooleanField(default=True, help_text='When saved, AI reads the brief and proposes the interests it suits. You can change them.', verbose_name='Let AI suggest interests')),
                ('link_label', models.CharField(blank=True, default='Book / learn more', max_length=60)),
                ('link_url', models.URLField(blank=True)),
                ('frequency', models.CharField(choices=[('once', 'Once'), ('daily', 'Every day'), ('weekly', 'Every week'), ('fortnightly', 'Every two weeks'), ('monthly', 'Every month')], default='once', help_text='Once means it only goes when you press Run. Anything else runs on the scheduler between the dates.', max_length=20)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('send_hour', models.PositiveSmallIntegerField(default=9)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active — runs on its schedule'), ('paused', 'Paused')], default='draft', max_length=20)),
                ('last_run_on', models.DateField(blank=True, editable=False, null=True)),
                ('runs', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audience_tags', models.ManyToManyField(blank=True, help_text='Readers who picked at least one of these interests.', related_name='saved_templates', to='opportunities.tag')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_templates', to=settings.AUTH_USER_MODEL)),
                ('readers', models.ManyToManyField(blank=True, help_text='Specific readers, if you picked them by hand. Combined with the rules below.', related_name='saved_templates', to='readers.reader')),
            ],
            options={
                'verbose_name': 'template',
                'ordering': ['-updated_at'],
            },
        ),
    ]
