# Generated by Django 5.1.15 on 2026-09-09 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_savedtemplate'),
        ('opportunities', '0007_alter_opportunity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='event',
            field=models.ForeignKey(blank=True, help_text='The event this campaign is about, if any. Its facts are the brief.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='opportunities.opportunity'),
        ),
    ]
