# Generated by Django 5.1.15 on 2026-09-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_campaign_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='angle',
            field=models.CharField(blank=True, help_text='The take, in a few words - who this is for and why. Kept when you run the campaign again for another event.', max_length=200),
        ),
        migrations.DeleteModel(
            name='SavedTemplate',
        ),
    ]
