# Generated by Django 5.1.15 on 2026-09-04 07:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('loved_examples', models.TextField(blank=True, help_text='Free text: things this reader has loved (shows, exhibitions, meals, etc).')),
                ('disliked_examples', models.TextField(blank=True, help_text="Free text: things this reader hasn't enjoyed.")),
                ('location', models.CharField(help_text="City or area, e.g. 'London'.", max_length=120)),
                ('travel_radius', models.CharField(choices=[('local_only', 'Only things close by'), ('within_city', 'Anywhere in my city'), ('regional', "I'll travel regionally for the right thing"), ('anywhere', "I'll travel far for something special")], max_length=20)),
                ('budget', models.CharField(choices=[('free_cheap', 'Free / very cheap'), ('moderate', 'Moderate'), ('treat', 'Happy to treat myself'), ('no_limit', "Budget isn't a constraint")], max_length=20)),
                ('availability', models.JSONField(blank=True, default=list, help_text="List of Availability values, e.g. ['weekends', 'weekday_evenings'].")),
                ('mainstream_preference', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='1 = strongly prefers mainstream/crowd-pleasing, 5 = strongly prefers niche/unusual.')),
                ('scale_preference', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='1 = prefers intimate/small-scale, 5 = prefers big/large-scale.')),
                ('is_active', models.BooleanField(default=True, help_text='Unchecked = unsubscribed.')),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interest_tags', models.ManyToManyField(blank=True, help_text='Interests picked during onboarding.', related_name='interested_readers', to='opportunities.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
