# Generated by Django 5.1.15 on 2026-09-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reader',
            name='open_to_surprise',
            field=models.BooleanField(default=False, help_text='Happy to occasionally get a wildcard pick outside their usual taste.'),
        ),
        migrations.AddField(
            model_name='reader',
            name='travel_destinations',
            field=models.TextField(blank=True, help_text='Free text: places they love to travel to, or would love to visit.'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='budget',
            field=models.CharField(blank=True, choices=[('free_cheap', 'Free / very cheap'), ('moderate', 'Moderate'), ('treat', 'Happy to treat myself'), ('no_limit', "Budget isn't a constraint")], max_length=20),
        ),
        migrations.AlterField(
            model_name='reader',
            name='location',
            field=models.CharField(blank=True, help_text="Where they live - city or area, e.g. 'London'.", max_length=120),
        ),
        migrations.AlterField(
            model_name='reader',
            name='mainstream_preference',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='1 = strongly prefers mainstream/crowd-pleasing, 5 = strongly prefers niche/unusual. Blank = no stated preference.', null=True),
        ),
        migrations.AlterField(
            model_name='reader',
            name='scale_preference',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='1 = prefers intimate/small-scale, 5 = prefers big/large-scale. Blank = no stated preference.', null=True),
        ),
        migrations.AlterField(
            model_name='reader',
            name='travel_radius',
            field=models.CharField(blank=True, choices=[('local_only', 'Only things close by'), ('within_city', 'Anywhere in my city'), ('regional', "I'll travel regionally for the right thing"), ('anywhere', "I'll travel far for something special")], max_length=20),
        ),
    ]
