# Generated by Django 5.1.15 on 2026-09-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0002_reader_age_reader_open_to_surprise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='interest_categories',
            field=models.JSONField(blank=True, default=list, help_text="Broad categories picked during onboarding, e.g. ['music', 'theatre']. Also decides which interest tags they're offered."),
        ),
    ]
