# Generated by Django 5.1.15 on 2026-09-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_seed_interest_taxonomy'),
        ('readers', '0003_reader_interest_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='ai_avoid_tags',
            field=models.ManyToManyField(blank=True, help_text="Things they signalled they don't want, inferred from free text.", related_name='ai_avoiding_readers', to='opportunities.tag'),
        ),
        migrations.AddField(
            model_name='reader',
            name='ai_inferred_tags',
            field=models.ManyToManyField(blank=True, help_text='Interests inferred from free text, not explicitly picked.', related_name='ai_inferred_readers', to='opportunities.tag'),
        ),
        migrations.AddField(
            model_name='reader',
            name='ai_profile_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reader',
            name='ai_taste_summary',
            field=models.TextField(blank=True, help_text="AI reading of this reader's free text, for editors and for writing their recommendations."),
        ),
    ]
