# Generated by Django 5.1.15 on 2026-09-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0004_reader_ai_avoid_tags_reader_ai_inferred_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='notes',
            field=models.TextField(blank=True, help_text="Anything the reader wanted to tell us, in their own words. Open-ended, so it's the place they can say things the rest of the questionnaire has no field for. Fed into matching via AI interpretation, and into the wording of their recommendations."),
        ),
    ]
