# Generated by Django 5.1.15 on 2026-09-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0005_reader_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='other_availability',
            field=models.TextField(blank=True, help_text="When they're free, in their own words."),
        ),
        migrations.AddField(
            model_name='reader',
            name='other_budget',
            field=models.TextField(blank=True, help_text='Their budget in their own words, e.g. ranges or exceptions.'),
        ),
        migrations.AddField(
            model_name='reader',
            name='other_categories',
            field=models.TextField(blank=True, help_text='Categories the reader typed in themselves.'),
        ),
        migrations.AddField(
            model_name='reader',
            name='other_interests',
            field=models.TextField(blank=True, help_text='Interests not in the tag taxonomy, in their words.'),
        ),
        migrations.AddField(
            model_name='reader',
            name='other_travel',
            field=models.TextField(blank=True, help_text="How far they'll travel, in their own words."),
        ),
    ]
