# Generated by Django 5.1.15 on 2026-09-07 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0007_reader_edit_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='edit_token',
        ),
    ]
