# Generated by Django 5.1.15 on 2026-09-18 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0010_new_releases_means_cinema'),
        ('readers', '0008_remove_reader_edit_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_radius', models.CharField(blank=True, choices=[('local_only', 'Only things close by'), ('within_city', 'Anywhere in my city'), ('regional', "I'll travel regionally for the right thing"), ('anywhere', "I'll travel far for something special")], help_text="How far they'll go for this one. Blank = their usual.", max_length=20)),
                ('budget', models.CharField(blank=True, choices=[('free_cheap', 'Free / very cheap'), ('moderate', 'Moderate'), ('treat', 'Happy to treat myself'), ('no_limit', "Budget isn't a constraint")], help_text="What they'll spend on this one. Blank = their usual.", max_length=20)),
                ('scale_preference', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='1 = intimate, 5 = large-scale, for this interest. Blank = their usual.', null=True)),
                ('mainstream_preference', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='1 = mainstream, 5 = niche, for this interest. Blank = their usual.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_preferences', to='readers.reader')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader_preferences', to='opportunities.tag')),
            ],
            options={
                'ordering': ['tag__name'],
                'constraints': [models.UniqueConstraint(fields=('reader', 'tag'), name='one_preference_per_interest')],
            },
        ),
    ]
