# Generated by Django 5.1.15 on 2026-09-25 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0010_new_releases_means_cinema'),
        ('readers', '0009_interest_preferences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interestpreference',
            options={'ordering': ['category', 'tag__name']},
        ),
        migrations.RemoveConstraint(
            model_name='interestpreference',
            name='one_preference_per_interest',
        ),
        migrations.AddField(
            model_name='interestpreference',
            name='category',
            field=models.CharField(blank=True, choices=[('theatre', 'Theatre'), ('music', 'Music'), ('film', 'Film'), ('exhibition', 'Exhibition'), ('talk', 'Talk / lecture'), ('food', 'Food & drink'), ('event', 'Event'), ('unusual', 'Unusual experience'), ('book', 'Books'), ('listen', 'New music'), ('watch', 'TV & streaming'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='interestpreference',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reader_preferences', to='opportunities.tag'),
        ),
        migrations.AddConstraint(
            model_name='interestpreference',
            constraint=models.UniqueConstraint(condition=models.Q(('tag__isnull', False)), fields=('reader', 'tag'), name='one_preference_per_interest'),
        ),
        migrations.AddConstraint(
            model_name='interestpreference',
            constraint=models.UniqueConstraint(condition=models.Q(('category', ''), _negated=True), fields=('reader', 'category'), name='one_preference_per_category'),
        ),
        migrations.AddConstraint(
            model_name='interestpreference',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category', ''), ('tag__isnull', False)), models.Q(('tag__isnull', True), models.Q(('category', ''), _negated=True)), _connector='OR'), name='preference_names_one_thing'),
        ),
    ]
