# Generated by Django 5.1.15 on 2026-09-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0010_preferences_by_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestpreference',
            name='availability',
            field=models.JSONField(blank=True, default=list, help_text="When they're free for this one, e.g. ['weekends']. Empty = their usual."),
        ),
    ]
