# Generated by Django 5.1.15 on 2026-09-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0011_preference_availability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interestpreference',
            options={'ordering': ['rank', 'category', 'tag__name']},
        ),
        migrations.AddField(
            model_name='interestpreference',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Where they put this among everything they picked: 1 = matters most.', null=True),
        ),
    ]
