# Generated by Django 5.1.15 on 2026-09-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0012_interest_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestpreference',
            name='category',
            field=models.CharField(blank=True, choices=[('theatre', 'Theatre'), ('music', 'Music'), ('film', 'Film'), ('exhibition', 'Exhibition'), ('talk', 'Talk / lecture'), ('food', 'Food & drink'), ('event', 'Event'), ('sport', 'Sport'), ('unusual', 'Unusual experience'), ('book', 'Books'), ('listen', 'New music'), ('watch', 'TV & streaming'), ('other', 'Other')], max_length=30),
        ),
    ]
