# Generated by Django 5.1.15 on 2026-09-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0013_sport_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestpreference',
            name='love',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How much it matters to them, 1-10: the size of its bubble at signup. The rank is worked out from these.', null=True),
        ),
    ]
