# Generated by Django 5.1.15 on 2026-09-07 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='The Ether', max_length=80)),
                ('tagline', models.CharField(default='a handful of things worth your time, picked for you.', help_text='Shown in the site footer and at the foot of the newsletter.', max_length=200)),
                ('hero_eyebrow', models.CharField(default='Personalised. Weekly. Worth it.', max_length=120)),
                ('hero_headline', models.CharField(default='Culture, curated just for you.', max_length=200)),
                ('hero_subhead', models.TextField(default="A handful of things to see, hear, eat and do — matched to your taste, your budget, and your week. Not everyone's.")),
                ('recommendations_per_send', models.PositiveSmallIntegerField(default=4, help_text='How many picks go in one newsletter. The brief calls for a small number with high confidence, not volume.', validators=[django.core.validators.MinValueValidator(1)])),
                ('min_recommendations', models.PositiveSmallIntegerField(default=2, help_text='Below this many strong matches, a reader is skipped entirely rather than sent a padded-out issue.', validators=[django.core.validators.MinValueValidator(1)])),
                ('cooldown_days', models.PositiveSmallIntegerField(default=60, help_text="Don't recommend the same opportunity to a reader again within this many days.")),
                ('email_from', models.CharField(blank=True, help_text='Sender for the newsletter, e.g. "The Ether &lt;hello@example.com&gt;". Blank uses the EMAIL_FROM environment variable. Must be a verified sender in SendGrid or sends are rejected.', max_length=200)),
                ('subject_template', models.CharField(default="{name}{count} things you'll probably love this week", help_text='Placeholders: {name} (ends with a comma and space, or empty) and {count}.', max_length=200)),
                ('weight_tag_overlap', models.FloatField(default=2.0, help_text="Per interest tag shared with the reader's own picks.")),
                ('weight_category', models.FloatField(default=1.5, help_text='When the category is one the reader follows.')),
                ('weight_inferred_tag', models.FloatField(default=0.9, help_text='Per tag AI inferred from their free text. Keep below the tag overlap weight: they told us the one, we guessed the other.')),
                ('penalty_avoid_tag', models.FloatField(default=2.0, help_text='Subtracted when a tag AI flagged as unwanted appears.')),
                ('weight_critic_rating', models.FloatField(default=0.2, help_text='Multiplied by the critic rating out of 5.')),
                ('penalty_price_step', models.FloatField(default=0.6, help_text="Per price tier away from the reader's budget.")),
                ('max_price_distance', models.PositiveSmallIntegerField(default=2, help_text='Beyond this many tiers from their budget, exclude entirely.')),
                ('penalty_mainstream_gap', models.FloatField(default=0.4, help_text='Per point of difference on the mainstream/unusual dial.')),
                ('penalty_scale_gap', models.FloatField(default=0.3, help_text='Per point of difference on the intimate/large-scale dial.')),
                ('penalty_out_of_area', models.FloatField(default=1.5, help_text="For an opportunity outside the reader's own area.")),
                ('feedback_more_like_this', models.FloatField(default=1.0)),
                ('feedback_saved', models.FloatField(default=0.6)),
                ('feedback_booked', models.FloatField(default=1.2)),
                ('feedback_not_for_me', models.FloatField(default=-1.0)),
                ('dislike_drop_threshold', models.FloatField(default=-1.0, help_text="Once a reader's accumulated dislike for a tag cluster falls below this, drop it entirely instead of just down-ranking.")),
                ('ai_enabled', models.BooleanField(default=True, help_text='Master switch. Off means everything uses the deterministic templates. Needs OPENAI_API_KEY set regardless.')),
                ('ai_write_rationales', models.BooleanField(default=True, help_text="Write the 'why this suits you' line for each pick.")),
                ('ai_interpret_readers', models.BooleanField(default=True, help_text='Read reader free text into taste signals.')),
                ('ai_classify_opportunities', models.BooleanField(default=True, help_text='Suggest tags and attributes for new listings.')),
                ('ai_model', models.CharField(blank=True, help_text='Blank uses the OPENAI_MODEL environment variable.', max_length=80)),
                ('ai_timeout_seconds', models.FloatField(default=8.0, help_text='Ceiling on a single AI call. Sends can run inside a web request, where an overrunning call gets the worker killed.')),
                ('ai_send_budget_seconds', models.FloatField(default=15.0, help_text='Total AI time for one newsletter. Once spent, remaining picks use the template.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site configuration',
                'verbose_name_plural': 'site configuration',
            },
        ),
    ]
