# Generated by Django 5.1.15 on 2026-09-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_headline',
            field=models.CharField(default='The cultural world, filtered.', help_text='The line under the name in the hero. Keep it short - it sits at display size.', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_subhead',
            field=models.TextField(default='Theatre, music, film, exhibitions, talks, food and the genuinely odd — narrowed each week to a handful chosen for your taste, your budget and the time you actually have.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='tagline',
            field=models.CharField(default="the cultural world, filtered down to what's worth your time.", help_text='Shown in the site footer and at the foot of the newsletter.', max_length=200),
        ),
    ]
