# Generated by Django 5.1.15 on 2026-09-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0002_alter_siteconfig_hero_headline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='send_welcome_email',
            field=models.BooleanField(default=True, help_text='Email a confirmation the moment someone signs up, showing back what they told us and how to change it.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='welcome_subject',
            field=models.CharField(default="You're in - welcome to {site}", help_text='Subject for the welcome email. {site} is replaced with the site name.', max_length=200),
        ),
    ]
