# Generated by Django 5.1.15 on 2026-09-07 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0003_siteconfig_send_welcome_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="For you, not the reader - e.g. 'Newsletter, shorter intro'.", max_length=120)),
                ('kind', models.CharField(choices=[('welcome', 'Welcome email'), ('newsletter', 'Newsletter')], max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Blank uses the subject from the site configuration.', max_length=200)),
                ('html_body', models.TextField(help_text='The HTML version. This is what most readers see.')),
                ('text_body', models.TextField(blank=True, help_text='The plain-text version. Worth keeping - some clients show it, and having one helps deliverability.')),
                ('notes', models.TextField(blank=True, help_text='Anything you want to remember about this version.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'email template',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='last_sent_on',
            field=models.DateField(blank=True, help_text="Set automatically after a scheduled run, so a cadence isn't repeated if the trigger fires more than once a day.", null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='send_day_of_month',
            field=models.PositiveSmallIntegerField(default=1, help_text='Which date it goes out on, for monthly (1-28).'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='send_frequency',
            field=models.CharField(choices=[('manual', 'Only when I trigger it'), ('weekly', 'Weekly'), ('fortnightly', 'Every two weeks'), ('monthly', 'Monthly')], default='manual', help_text='How often the newsletter goes out. Anything other than manual needs something to call send_newsletters daily - see the note below.', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='send_weekday',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=3, help_text='Which day it goes out on, for weekly and fortnightly.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='newsletter_template',
            field=models.ForeignKey(blank=True, help_text='Leave empty to use the built-in newsletter.', limit_choices_to={'kind': 'newsletter'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='siteconfig.emailtemplate'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='welcome_template',
            field=models.ForeignKey(blank=True, help_text='Leave empty to use the built-in welcome email.', limit_choices_to={'kind': 'welcome'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='siteconfig.emailtemplate'),
        ),
    ]
