# Generated by Django 5.1.15 on 2026-09-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0004_emailtemplate_siteconfig_last_sent_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='subject_template',
            field=models.CharField(default='{name}{count} thing{plural} worth your time', help_text="Placeholders: {name} (their first name plus a comma, or empty), {first_name} (bare), {count}, and {plural} (an 's' unless there is exactly one pick - so 'thing{plural}' reads correctly either way).", max_length=200),
        ),
    ]
