# Generated by Django 5.1.15 on 2026-09-07 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0005_alter_siteconfig_subject_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='ai_write_campaigns',
            field=models.BooleanField(default=True, help_text="Write each reader's version of a campaign email from your brief."),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='campaign_template',
            field=models.ForeignKey(blank=True, help_text='Leave empty to use the built-in campaign email.', limit_choices_to={'kind': 'campaign'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='siteconfig.emailtemplate'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='send_hour',
            field=models.PositiveSmallIntegerField(default=8, help_text="Hour of the day it goes out from, 0-23, in the site's time zone (UTC unless changed in settings). The scheduler sends on its first pass after this hour on a send day."),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='kind',
            field=models.CharField(choices=[('welcome', 'Welcome email'), ('newsletter', 'Newsletter'), ('campaign', 'Campaign')], max_length=20),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='send_frequency',
            field=models.CharField(choices=[('manual', 'Only when I trigger it'), ('weekly', 'Weekly'), ('fortnightly', 'Every two weeks'), ('monthly', 'Monthly')], default='manual', help_text='How often the newsletter goes out. The scheduler checks every 15 minutes and sends on the day and hour set here.', max_length=20),
        ),
    ]
