# Generated by Django 5.1.15 on 2026-09-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0006_siteconfig_ai_write_campaigns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='send_frequency',
            field=models.CharField(choices=[('manual', 'Only when I trigger it'), ('weekly', 'Weekly'), ('fortnightly', 'Every two weeks'), ('monthly', 'Monthly')], default='manual', help_text='How often the newsletter goes out. The scheduler checks every few minutes and sends on the day and hour set here.', max_length=20),
        ),
    ]
