# Generated by Django 5.1.15 on 2026-09-09 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0007_alter_siteconfig_send_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='min_recommendations',
            field=models.PositiveSmallIntegerField(default=1, help_text='Below this many strong matches, a reader is skipped entirely rather than sent a padded-out issue. One means a single good match is worth sending - right while the catalogue is small; raise it once there is more to choose from.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
