# Generated by Django 5.1.15 on 2026-09-17 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0008_alter_siteconfig_min_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='ai_issue_timeout_seconds',
            field=models.FloatField(default=180.0, help_text='Ceiling on writing one whole culture week. It runs in the background, never inside a page, so it can take its time.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='book_ahead_days',
            field=models.PositiveSmallIntegerField(default=120, help_text='How far ahead Book ahead looks, in days.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='book_ahead_max',
            field=models.PositiveSmallIntegerField(default=2, help_text='How many things further off go in Book ahead. 0 turns it off.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='carry_forward_saved',
            field=models.BooleanField(default=True, help_text='Bring back things a reader pressed Save on while they are still on, even inside the cooldown - more urgently as they near closing.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='max_per_section',
            field=models.PositiveSmallIntegerField(default=4, help_text='The most picks in any one section below the top, e.g. Live music.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='min_for_you_stars',
            field=models.DecimalField(decimal_places=1, default=3, help_text='The lowest FOR YOU rating, out of 5, that makes it into an issue.', max_digits=2),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='top_picks_count',
            field=models.PositiveSmallIntegerField(default=5, help_text='How many picks open the issue, written up in full. No more than two from any one category.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='recommendations_per_send',
            field=models.PositiveSmallIntegerField(default=20, help_text='The most picks one culture week can hold, across every section. A cap, not a target: sections with nothing good enough are left out rather than padded.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='subject_template',
            field=models.CharField(default='{possessive}culture week: {week}', help_text='Placeholders: {possessive} ("Maya\'s ", or "Your " with no name), {week} (e.g. Thursday 17–Wednesday 23 September), {name} (their first name plus a comma, or empty), {first_name} (bare), {count}, and {plural} (an \'s\' unless there is exactly one pick).', max_length=200),
        ),
    ]
