# Generated by Django 5.1.15 on 2026-09-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0010_culture_week_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='weight_interest_rank',
            field=models.FloatField(default=2.0, help_text="Added for the reader's first-ranked interest, shrinking evenly to nothing for their last. How much the order they put things in counts."),
        ),
    ]
