# Generated by Django 5.1.15 on 2026-09-04 07:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0001_initial'),
        ('readers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('resend_message_id', models.CharField(blank=True, max_length=120)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='readers.reader')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rationale', models.TextField(help_text='Short reader-facing explanation of why this fits.')),
                ('score', models.FloatField(default=0, help_text='Internal matching score, for debugging/tuning.')),
                ('feedback', models.CharField(choices=[('none', 'No feedback yet'), ('more_like_this', 'More like this'), ('not_for_me', 'Not for me'), ('save', 'Save'), ('booked', 'Booked')], default='none', max_length=20)),
                ('feedback_at', models.DateTimeField(blank=True, null=True)),
                ('feedback_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommendations.newsletterissue')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='opportunities.opportunity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
