# Generated by Django 5.1.15 on 2026-09-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_rename_resend_message_id_to_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='verdict',
            field=models.CharField(blank=True, help_text="The editorial call, e.g. 'GO.' or 'I think you'll love this.'", max_length=200),
        ),
    ]
