# Generated by Django 5.1.15 on 2026-09-09 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_ends_on_campaign_frequency_and_more'),
        ('readers', '0008_remove_reader_edit_token'),
        ('recommendations', '0003_recommendation_verdict'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('booking', 'Booking link on a pick'), ('feedback', 'Feedback button'), ('campaign', 'Campaign button'), ('other', 'Something else')], default='other', max_length=20)),
                ('url', models.TextField()),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_clicks', to='campaigns.campaign')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_clicks', to='readers.reader')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_clicks', to='recommendations.recommendation')),
            ],
            options={
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['section', 'clicked_at'], name='recommendat_section_88bbf6_idx')],
            },
        ),
    ]
