# Generated by Django 5.1.15 on 2026-09-17 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0008_remove_reader_edit_token'),
        ('recommendations', '0004_linkclick'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterissue',
            name='closing',
            field=models.TextField(blank=True, help_text='The closing line: the strongest bets.'),
        ),
        migrations.AddField(
            model_name='newsletterissue',
            name='intro',
            field=models.TextField(blank=True, help_text="The editor's note at the top."),
        ),
        migrations.AddField(
            model_name='newsletterissue',
            name='programme',
            field=models.JSONField(blank=True, default=list, help_text='If I were programming your week: [{day, plan}].'),
        ),
        migrations.AddField(
            model_name='newsletterissue',
            name='week_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsletterissue',
            name='week_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='caveat',
            field=models.TextField(blank=True, help_text='Anything worth knowing before going: length, sold-out runs, mixed reviews. Empty when there is nothing.'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='for_you_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='FOR YOU, out of 5 with halves: how strongly this reader should consider it.', max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='is_top',
            field=models.BooleanField(default=False, help_text='One of the picks at the top of the issue.'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='section',
            field=models.CharField(blank=True, help_text='Where in the issue it sits: top, a category, book ahead.', max_length=20),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='timing',
            field=models.CharField(blank=True, help_text='last_chance, new, one_night, on, release, book_ahead, saved.', max_length=20),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='timing_label',
            field=models.CharField(blank=True, help_text="As printed, e.g. 'Closes Sat 19 Sep'.", max_length=80),
        ),
        migrations.AlterField(
            model_name='linkclick',
            name='section',
            field=models.CharField(choices=[('booking', 'Booking link on a pick'), ('review', 'Critic review link on a pick'), ('feedback', 'Feedback button'), ('campaign', 'Campaign button'), ('other', 'Something else')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='verdict',
            field=models.CharField(blank=True, help_text="The opening line: the editor's call on it, e.g. 'This is probably my best live-music bet for you this week.'", max_length=200),
        ),
        migrations.CreateModel(
            name='IssueDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('building', 'Writing'), ('ready', 'Ready'), ('empty', 'Nothing to send'), ('failed', 'Failed'), ('sending', 'Sending'), ('sent', 'Sent')], default='building', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('pool', models.JSONField(blank=True, help_text='The event ids it was built from, or null for everything.', null=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('send_when_ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommendations.newsletterissue')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='readers.reader')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReaderReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='recommendations.newsletterissue')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='readers.reader')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='recommendations.recommendation')),
            ],
            options={
                'verbose_name_plural': 'reader replies',
                'ordering': ['-created_at'],
            },
        ),
    ]
