# Generated by Django 5.1.15 on 2026-09-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_culture_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterissue',
            name='section_notes',
            field=models.JSONField(blank=True, default=dict, help_text="A line under a section heading, by section key: 'There isn't a big album this week…'"),
        ),
        migrations.AddField(
            model_name='newsletterissue',
            name='strongest',
            field=models.JSONField(blank=True, default=list, help_text='Event ids of the strongest bets, best first.'),
        ),
    ]
