# Generated by Django 5.1.15 on 2026-09-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0006_issue_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='helpful',
            field=models.BooleanField(blank=True, help_text='Did this pick help them? Blank = not answered.', null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='helpful_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
